<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AdminsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('admins')->delete();
        
        \DB::table('admins')->insert(array (
            0 => 
            array (
                'id' => 1,
                'rank_id' => 4,
                'identification' => 'yeah',
                'name' => '예지사',
                'email' => NULL,
                'phone_number' => '010-0000-0000',
                'phone_first' => NULL,
                'phone_center' => NULL,
                'phone_last' => NULL,
                'resident_registration_number' => NULL,
                'password' => '$2y$10$npMK/3kbNSyEZyLwuK612OQloSY8oiD75j.GwictJhuxZRC..F2e2',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'rank_id' => 4,
                'identification' => 'toy',
                'name' => 'Supplier',
                'email' => NULL,
                'phone_number' => '010-1111-1111',
                'phone_first' => NULL,
                'phone_center' => NULL,
                'phone_last' => NULL,
                'resident_registration_number' => NULL,
                'password' => '$2y$10$mbqW15qgOQb58dvBqdQtee83mxgW9ZlDDz/6ifGEEbKRiPPeSZs6m',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'rank_id' => 4,
                'identification' => 'snack',
                'name' => '과자',
                'email' => NULL,
                'phone_number' => '010-2222-2222',
                'phone_first' => NULL,
                'phone_center' => NULL,
                'phone_last' => NULL,
                'resident_registration_number' => NULL,
                'password' => '$2y$10$npMK/3kbNSyEZyLwuK612OQloSY8oiD75j.GwictJhuxZRC..F2e2',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'rank_id' => 4,
                'identification' => 'jewelry',
                'name' => '주얼리',
                'email' => NULL,
                'phone_number' => '010-3333-3333',
                'phone_first' => NULL,
                'phone_center' => NULL,
                'phone_last' => NULL,
                'resident_registration_number' => NULL,
                'password' => '$2y$10$npMK/3kbNSyEZyLwuK612OQloSY8oiD75j.GwictJhuxZRC..F2e2',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'rank_id' => 4,
                'identification' => 'saida',
                'name' => '롯데칠성',
                'email' => NULL,
                'phone_number' => '010-4444-4444',
                'phone_first' => NULL,
                'phone_center' => NULL,
                'phone_last' => NULL,
                'resident_registration_number' => NULL,
                'password' => '$2y$10$npMK/3kbNSyEZyLwuK612OQloSY8oiD75j.GwictJhuxZRC..F2e2',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'rank_id' => 1,
                'identification' => 'admin',
                'name' => '관리자',
                'email' => NULL,
                'phone_number' => '010-1234-1234',
                'phone_first' => NULL,
                'phone_center' => NULL,
                'phone_last' => NULL,
                'resident_registration_number' => NULL,
                'password' => '$2y$10$npMK/3kbNSyEZyLwuK612OQloSY8oiD75j.GwictJhuxZRC..F2e2',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'rank_id' => 3,
                'identification' => 'allnight',
                'name' => 'GieJung',
                'email' => NULL,
                'phone_number' => '010-1234-1235',
                'phone_first' => NULL,
                'phone_center' => NULL,
                'phone_last' => NULL,
                'resident_registration_number' => NULL,
                'password' => '$2y$10$npMK/3kbNSyEZyLwuK612OQloSY8oiD75j.GwictJhuxZRC..F2e2',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 67,
                'rank_id' => 3,
                'identification' => 'tienowner',
                'name' => 'tien_chucuahang',
                'email' => 'luongkimtien@enjoyworks.co.kr',
                'phone_number' => '101-0101-1010',
                'phone_first' => '101',
                'phone_center' => '0101',
                'phone_last' => '1010',
                'resident_registration_number' => '1313',
                'password' => '$2y$10$rFmAPCb9nC4d0Mm87pyCWOmNSUYSajTlSQLlX40HkMzIbBPGS69F6',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-03-12 13:22:06',
                'updated_at' => '2021-03-12 14:42:31',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 68,
                'rank_id' => 3,
                'identification' => 'shopqa1',
                'name' => 'shopduc',
                'email' => 'shopqa1@gmail.com',
                'phone_number' => '035-3958-3195',
                'phone_first' => '035',
                'phone_center' => '3958',
                'phone_last' => '3195',
                'resident_registration_number' => '3599202353259',
                'password' => '$2y$10$6Jg74pIUvm.qkFwUdIe3J.VpoZz5G8bJN3LnFlMgkVCL0bZpKr5Xu',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-03-12 13:23:02',
                'updated_at' => '2021-03-12 13:23:02',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 69,
                'rank_id' => 1,
                'identification' => '최고관리자',
                'name' => '최고',
                'email' => '',
                'phone_number' => '010-1123-2322',
                'phone_first' => '010',
                'phone_center' => '1123',
                'phone_last' => '2322',
                'resident_registration_number' => '',
                'password' => '$2y$10$QCnpq7tDf8v0aib3quIr7OXfAIpqfydm4lxsF0pTh0tPW2ByNDbxq',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-03-12 13:40:17',
                'updated_at' => '2021-03-12 13:40:17',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 70,
                'rank_id' => 4,
                'identification' => 'Supplierqa1',
                'name' => 'Supplierqa',
                'email' => 'Supplierqa1@gmail.com',
                'phone_number' => '354-2525-5353',
                'phone_first' => '354',
                'phone_center' => '2525',
                'phone_last' => '5353',
                'resident_registration_number' => '13091293',
                'password' => '$2y$10$6Jg74pIUvm.qkFwUdIe3J.VpoZz5G8bJN3LnFlMgkVCL0bZpKr5Xu',
                'bank_information' => 'TichBank',
                'virtual_account_information' => 'Lee jo Oc',
                'holding_deposit' => NULL,
                'affiliate_name' => 'SupplierQA',
                'account_number' => '3414134141413',
                'firebase_token' => NULL,
                'created_at' => '2021-03-12 14:47:32',
                'updated_at' => '2021-04-07 15:04:27',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 71,
                'rank_id' => 4,
                'identification' => 'tien_supper',
                'name' => 'tien_supper',
                'email' => 'luongkimtien@gmail.com',
                'phone_number' => '120-1231-1231',
                'phone_first' => '120',
                'phone_center' => '1231',
                'phone_last' => '1231',
                'resident_registration_number' => '21313113',
                'password' => '$2y$10$Kh.Un6VPlf2jG8StmdyT1uOeeRygkhWqHASHV1KF/POryKa82zM5e',
                'bank_information' => 'TP-bank',
                'virtual_account_information' => '03131313311',
                'holding_deposit' => NULL,
                'affiliate_name' => 'tien',
                'account_number' => '210251255125',
                'firebase_token' => NULL,
                'created_at' => '2021-03-12 15:11:09',
                'updated_at' => '2021-03-22 15:30:19',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 72,
                'rank_id' => 1,
                'identification' => 'PQA',
                'name' => 'PQA테스트',
                'email' => '',
                'phone_number' => '010-3423-5828',
                'phone_first' => '010',
                'phone_center' => '3423',
                'phone_last' => '5828',
                'resident_registration_number' => '',
                'password' => '$2y$10$Fu4VA8vqfh/SXuPgjJu.nehH9TkSmBPQhfq6qR2sr1Jk2v9BtGMNq',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-03-15 10:38:17',
                'updated_at' => '2021-03-15 10:38:47',
                'deleted_at' => '2021-03-15 10:38:47',
            ),
            13 => 
            array (
                'id' => 75,
                'rank_id' => 1,
                'identification' => 'PQA',
                'name' => 'PQA테스트',
                'email' => '',
                'phone_number' => '010-3341-5439',
                'phone_first' => '010',
                'phone_center' => '3341',
                'phone_last' => '5439',
                'resident_registration_number' => '',
                'password' => '$2y$10$OmG1qMz2zaeuzv2gNLztM.jjeEmfDrkZdAJ11QcKDPV2TjKyT10x6',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-03-15 11:07:07',
                'updated_at' => '2021-03-15 11:07:12',
                'deleted_at' => '2021-03-15 11:07:12',
            ),
            14 => 
            array (
                'id' => 76,
                'rank_id' => 1,
                'identification' => 'PQA',
                'name' => 'PQA테스트',
                'email' => '',
                'phone_number' => '010-5423-1212',
                'phone_first' => '010',
                'phone_center' => '5423',
                'phone_last' => '1212',
                'resident_registration_number' => '',
                'password' => '$2y$10$kQnHlTmUyRJO7C8hlG8CwONX3m4EohJ87kxRrDqFBwk8beV4dy5sm',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-03-15 11:07:25',
                'updated_at' => '2021-03-15 13:21:50',
                'deleted_at' => '2021-03-15 13:21:50',
            ),
            15 => 
            array (
                'id' => 77,
                'rank_id' => 1,
                'identification' => 'soonhyeon',
                'name' => '임순현',
                'email' => 'dlatnsgus@enjoyworks.co.kr',
                'phone_number' => '010-3874-3363',
                'phone_first' => '010',
                'phone_center' => '3874',
                'phone_last' => '3363',
                'resident_registration_number' => '112132144541',
                'password' => '$2y$10$tg33EmLOH6/gUSNZchZeae1gGt1q.SB.iIuE2p.dQsvy/uP.MzWIK',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-03-15 11:28:12',
                'updated_at' => '2021-03-15 11:28:12',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 78,
                'rank_id' => 3,
                'identification' => 'soonhyeon1',
                'name' => '임순현1',
                'email' => 'dlatnsgus@enjoyworks.co.kr',
                'phone_number' => '010-1515-1324',
                'phone_first' => '010',
                'phone_center' => '1515',
                'phone_last' => '1324',
                'resident_registration_number' => '454654',
                'password' => '$2y$10$24lGWMfwe9BoynL3g9u/zOKEaFtFzztlIF3Q1lshC7hZmPzPvqSFK',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-03-15 11:28:39',
                'updated_at' => '2021-03-15 11:28:39',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 79,
                'rank_id' => 2,
                'identification' => '박가맹',
                'name' => '박가맹',
                'email' => '',
                'phone_number' => '010-5311-5483',
                'phone_first' => '010',
                'phone_center' => '5311',
                'phone_last' => '5483',
                'resident_registration_number' => '',
                'password' => '$2y$10$fdrjRxil6zy1dEaWK0mzSuIdgpkYpQcSoAmxDr4hE7tZhZ47shVNO',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-03-15 13:18:00',
                'updated_at' => '2021-03-15 13:18:39',
                'deleted_at' => '2021-03-15 13:18:39',
            ),
            18 => 
            array (
                'id' => 80,
                'rank_id' => 1,
                'identification' => '박가맹',
                'name' => '박가맹',
                'email' => '',
                'phone_number' => '010-2745-0675',
                'phone_first' => '010',
                'phone_center' => '4212',
                'phone_last' => '4212',
                'resident_registration_number' => '',
                'password' => '$2y$10$TwK3LJo9XWd8Eq.oHKcZZeRVS6PIOfSM4fVq8lYnD..zJD9m2eBZ2',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-03-15 13:18:53',
                'updated_at' => '2021-03-15 13:18:57',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 81,
                'rank_id' => 4,
                'identification' => 'tien2_supper',
                'name' => 'Tien Luong',
                'email' => 'luongkimtienit198@gmail.com',
                'phone_number' => '234-2342-2342',
                'phone_first' => '234',
                'phone_center' => '2342',
                'phone_last' => '2342',
                'resident_registration_number' => '324',
                'password' => '$2y$10$GN7nhe5Xt757QTwL49MJMeh5ZyScBmXBm5FoVFIzgiZf/OuyPpOb2',
                'bank_information' => '234',
                'virtual_account_information' => '234',
                'holding_deposit' => NULL,
                'affiliate_name' => 'TIEN2-supper',
                'account_number' => '4',
                'firebase_token' => NULL,
                'created_at' => '2021-03-18 15:25:07',
                'updated_at' => '2021-03-18 15:25:07',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 82,
                'rank_id' => 4,
                'identification' => 'tien123',
                'name' => 'Tien Luong123',
                'email' => 'luongkimtienit198@gmail.com',
                'phone_number' => '123-1231-1231',
                'phone_first' => '123',
                'phone_center' => '1231',
                'phone_last' => '1231',
                'resident_registration_number' => '123123123123',
                'password' => '$2y$10$iwXXkgAzjfqUCMq1KPdS1uZruoNkSjYNG.ZCeJgoWe40UX5gVUsVq',
                'bank_information' => 'Tien Luong',
                'virtual_account_information' => '234',
                'holding_deposit' => NULL,
                'affiliate_name' => 'tien123',
                'account_number' => '1313',
                'firebase_token' => NULL,
                'created_at' => '2021-03-24 15:21:47',
                'updated_at' => '2021-03-24 15:21:47',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 83,
                'rank_id' => 2,
                'identification' => 'tien_admin',
                'name' => 'tienadmin',
                'email' => 'luongkimtien123@enjoyworks.co.kr',
                'phone_number' => '011-1231-1231',
                'phone_first' => '011',
                'phone_center' => '1231',
                'phone_last' => '1231',
                'resident_registration_number' => '121313',
                'password' => '$2y$10$ddi1zFihafHbvSCVwQ2Bu.tvYFjywuTAcSDhpz7PnrIaF.CeanBqy',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-03-24 15:47:18',
                'updated_at' => '2021-04-07 15:04:20',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 84,
                'rank_id' => 6,
                'identification' => 'tien1234',
                'name' => 'tien1234',
                'email' => 'luongkimtien123@gmail.com',
                'phone_number' => '123-1232-1312',
                'phone_first' => '123',
                'phone_center' => '1232',
                'phone_last' => '1312',
                'resident_registration_number' => '13',
                'password' => '$2y$10$st8VQwZW.JAjbrZcZBXFxeFbXo5Qsdt0fx8AB6e/vT3A7MmnW0RJ2',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-03-26 12:55:31',
                'updated_at' => '2021-03-26 12:55:31',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 85,
                'rank_id' => 3,
                'identification' => 'HSY',
                'name' => '박성영',
                'email' => '',
                'phone_number' => '010-1232-5221',
                'phone_first' => '010',
                'phone_center' => '1232',
                'phone_last' => '5221',
                'resident_registration_number' => '',
                'password' => '$2y$10$vG4vShujkjxn65xEPYalGOwk1E6mVpOVWNCjI1mZTeHPGwkpwLJ0S',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-03-26 14:20:04',
                'updated_at' => '2021-03-26 14:20:04',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 86,
                'rank_id' => 5,
                'identification' => 'tienad- kinhdoanh',
                'name' => 'tien',
                'email' => '',
                'phone_number' => '010-2131-1221',
                'phone_first' => '010',
                'phone_center' => '2131',
                'phone_last' => '1221',
                'resident_registration_number' => '',
                'password' => '$2y$10$K7oHAOTjbV/ECUjW4o654.KSPs.KgxuLteX9H8W6LWfLDtFSkmNki',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-07 16:17:21',
                'updated_at' => '2021-04-07 16:24:26',
                'deleted_at' => '2021-04-07 16:24:26',
            ),
            25 => 
            array (
                'id' => 87,
                'rank_id' => 5,
                'identification' => 'kimtien-kinhdoanh',
                'name' => 'tienq',
                'email' => 'luongkimtienit198@gmail.com',
                'phone_number' => '121-1212-1212',
                'phone_first' => '121',
                'phone_center' => '1212',
                'phone_last' => '1212',
                'resident_registration_number' => '',
                'password' => '$2y$10$Y3LxxUYXpPDjKj39trCJuegSnr5p6aux8xi1KoheEI2L7DtaaYP5.',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-07 16:21:02',
                'updated_at' => '2021-04-08 11:47:21',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 88,
                'rank_id' => 5,
                'identification' => 'tien-kd',
                'name' => 'tienkd',
                'email' => '',
                'phone_number' => '131-3123-1231',
                'phone_first' => '131',
                'phone_center' => '3123',
                'phone_last' => '1231',
                'resident_registration_number' => '',
                'password' => '$2y$10$c9kmxXhB02qYsBFuyUZBDuYTdr0HK5jJiwXhU2ny19EWstq0T.1.u',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-07 16:25:15',
                'updated_at' => '2021-04-08 15:09:51',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 89,
                'rank_id' => 5,
                'identification' => 'tien-kd1',
                'name' => 'tien123',
                'email' => 'luongkimtien@enjoyworks.co.kr',
                'phone_number' => '232-3232-2323',
                'phone_first' => '232',
                'phone_center' => '3232',
                'phone_last' => '2323',
                'resident_registration_number' => '',
                'password' => '$2y$10$6Jg74pIUvm.qkFwUdIe3J.VpoZz5G8bJN3LnFlMgkVCL0bZpKr5Xu',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-08 11:48:46',
                'updated_at' => '2021-04-08 11:53:31',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 90,
                'rank_id' => 5,
                'identification' => 'adminsale',
                'name' => 'adminsale',
                'email' => 'luongkimtien@enjoyworks.co.kr',
                'phone_number' => '122-1111-3333',
                'phone_first' => '122',
                'phone_center' => '1111',
                'phone_last' => '3333',
                'resident_registration_number' => '',
                'password' => '$2y$10$9TjNAr/5x9DKTPIbmeKmvOcqx/COJc3JHU/GLGLl4ZAlc1B1nvCiS',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-08 15:17:29',
                'updated_at' => '2021-04-08 16:31:25',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 91,
                'rank_id' => 3,
                'identification' => 'tienowner2',
                'name' => 'tien',
                'email' => '',
                'phone_number' => '111-1111-1111',
                'phone_first' => '111',
                'phone_center' => '1111',
                'phone_last' => '1111',
                'resident_registration_number' => '123123',
                'password' => '$2y$10$9dD11Ppda2Tc/JngcG68wO1NBA8nyk5EjRuazuw9O7uNizp.IUuOq',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-08 17:35:10',
                'updated_at' => '2021-04-08 17:35:10',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 92,
                'rank_id' => 5,
                'identification' => '영업',
                'name' => '영업',
                'email' => '',
                'phone_number' => '010-2128-9992',
                'phone_first' => '010',
                'phone_center' => '2128',
                'phone_last' => '9992',
                'resident_registration_number' => '',
                'password' => '$2y$10$Wsu0DvADDak1nTXvOoiH6.MO5Qq/hO7f7342sf8ctN/Fam/rtuJBO',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-09 13:31:34',
                'updated_at' => '2021-04-09 13:31:34',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 93,
                'rank_id' => 4,
                'identification' => 'soonhyeon2',
                'name' => '임순현2',
                'email' => '',
                'phone_number' => '010-1251-1235',
                'phone_first' => '010',
                'phone_center' => '1251',
                'phone_last' => '1235',
                'resident_registration_number' => '',
                'password' => '$2y$10$TWzFvmIt1z50SoxeJwSYXuga2kC5hgqjZZ4.HdhchoXaBcPuhnoqK',
                'bank_information' => '',
                'virtual_account_information' => '',
                'holding_deposit' => NULL,
                'affiliate_name' => '순현테스트',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-12 11:20:46',
                'updated_at' => '2021-04-20 16:50:05',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 94,
                'rank_id' => 5,
                'identification' => 'soonhyeon3',
                'name' => '임순현3',
                'email' => '',
                'phone_number' => '010-9941-1231',
                'phone_first' => '010',
                'phone_center' => '9941',
                'phone_last' => '1231',
                'resident_registration_number' => '',
                'password' => '$2y$10$nZs9eMk6s7HkydvIo0Ol.eQHZwJm92C5XZ.ih6P6hToZqjRhClZj6',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-12 11:23:00',
                'updated_at' => '2021-04-12 11:23:00',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 95,
                'rank_id' => 3,
                'identification' => 'tienphamstore',
                'name' => 'tienpham',
                'email' => 'tienphamstore@yopmail.com',
                'phone_number' => '092-1213-1212',
                'phone_first' => '092',
                'phone_center' => '1213',
                'phone_last' => '1212',
                'resident_registration_number' => '32432425324324',
                'password' => '$2y$10$7UiEJYnYZ4LGzKVR/erjE.yGeDs5nacMgmx28w4fsH/IeQP3hPg46',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-15 12:37:34',
                'updated_at' => '2021-04-15 12:37:34',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 96,
                'rank_id' => 3,
                'identification' => 'giakiet',
                'name' => 'giakiet',
                'email' => 'giakiet@tienpham.com',
                'phone_number' => '125-4522-5456',
                'phone_first' => '125',
                'phone_center' => '4522',
                'phone_last' => '5456',
                'resident_registration_number' => '987654321',
                'password' => '$2y$10$4ZY8Of.xhH7K3Es//81Mn.7mF5yNSET286rK8dgABlT5fPWjP8rXq',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-26 14:48:41',
                'updated_at' => '2021-04-26 14:48:41',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 97,
                'rank_id' => 5,
                'identification' => '영업test',
                'name' => '영업뛰자',
                'email' => '',
                'phone_number' => '010-0002-3646',
                'phone_first' => '010',
                'phone_center' => '0002',
                'phone_last' => '3646',
                'resident_registration_number' => '',
                'password' => '$2y$10$3LYbPNeJqDD5tHD/IQ9hW.zQ8fxZ2H2X8tTXR3lPTVIoghQ9PQPpq',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-29 10:09:20',
                'updated_at' => '2021-04-29 10:09:20',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 98,
                'rank_id' => 6,
                'identification' => 'alba',
                'name' => '중곡알바',
                'email' => '',
                'phone_number' => '000-1513-5419',
                'phone_first' => '000',
                'phone_center' => '1513',
                'phone_last' => '5419',
                'resident_registration_number' => '',
                'password' => '$2y$10$qNzVq8BykbRMM47lhKpM1Oy8zpUDo/hsXBn5SFlWJoNAMCxarLLRi',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-29 10:28:04',
                'updated_at' => '2021-04-29 10:28:04',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 99,
                'rank_id' => 6,
                'identification' => 'soonhyeon_alba',
                'name' => '순현알바',
                'email' => '',
                'phone_number' => '010-1111-2222',
                'phone_first' => '010',
                'phone_center' => '1111',
                'phone_last' => '2222',
                'resident_registration_number' => '2',
                'password' => '$2y$10$TU7g9o/.NOi0tkG.1oYOruAj35RE0bB.INpi0CvSGcdzFiTVLaOyW',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-29 13:11:37',
                'updated_at' => '2021-04-29 13:11:37',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 100,
                'rank_id' => 6,
                'identification' => '여러알바',
                'name' => '여러곳알바',
                'email' => '',
                'phone_number' => '035-5496-3513',
                'phone_first' => '035',
                'phone_center' => '5496',
                'phone_last' => '3513',
                'resident_registration_number' => '',
                'password' => '$2y$10$iFjvx917.0okbUIxoanImuOGl0wiHnRiixWbaan.mBCSaXlIXycOG',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-29 13:30:20',
                'updated_at' => '2021-04-29 13:30:20',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 101,
                'rank_id' => 1,
                'identification' => 'jeonginseon25',
                'name' => '정인선',
                'email' => 'jeonginseon25@enjoyworks.co.kr',
                'phone_number' => '010-5824-5702',
                'phone_first' => '010',
                'phone_center' => '5824',
                'phone_last' => '5702',
                'resident_registration_number' => '',
                'password' => '$2y$10$23drPWYfQsxHD/VUO.yOEu1qhydkawsHCbEYWOEHfTDhDDEnYPWc.',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-30 14:23:41',
                'updated_at' => '2021-04-30 14:37:10',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 102,
                'rank_id' => 3,
                'identification' => 'jeonginseon_가맹점주',
                'name' => '정인선_가맹점주',
                'email' => '',
                'phone_number' => '010-0251-5522',
                'phone_first' => '010',
                'phone_center' => '0251',
                'phone_last' => '5522',
                'resident_registration_number' => '',
                'password' => '$2y$10$YXVxkHNi07lYcCuMpWgMBebyuyY3Tbbx1XxPgwoGVZ5ZYsxO6y1r.',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-30 14:28:20',
                'updated_at' => '2021-04-30 14:29:47',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 103,
                'rank_id' => 4,
                'identification' => 'jeonginseon_공급',
                'name' => '정인선_공급',
                'email' => '',
                'phone_number' => '010-2155-2012',
                'phone_first' => '010',
                'phone_center' => '2155',
                'phone_last' => '2012',
                'resident_registration_number' => '',
                'password' => '$2y$10$gG/WaBg35Arz538bPJbby.mLGE31UpP6iJTuzOEx00BpQd2ixb7ZO',
                'bank_information' => '',
                'virtual_account_information' => '',
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-30 14:29:26',
                'updated_at' => '2021-04-30 14:29:26',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 104,
                'rank_id' => 5,
                'identification' => 'jeonginseon_영업',
                'name' => '정인선_영업',
                'email' => '',
                'phone_number' => '020-1211-1023',
                'phone_first' => '020',
                'phone_center' => '1211',
                'phone_last' => '1023',
                'resident_registration_number' => '',
                'password' => '$2y$10$adp8RMBz9pqsC9urpDTpL.iTRFTyj.UNoPgozQCbndgGNUo0CzTMa',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-30 14:32:28',
                'updated_at' => '2021-04-30 14:32:28',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 105,
                'rank_id' => 6,
                'identification' => 'jeonginseon_알바',
                'name' => '정인선_알바',
                'email' => '',
                'phone_number' => '020-2103-1220',
                'phone_first' => '020',
                'phone_center' => '2103',
                'phone_last' => '1220',
                'resident_registration_number' => '',
                'password' => '$2y$10$3thqNaLTns7n/LTjow2nbOVOOcogRdBXMp1D9BTuQTLWCdrB6FLxW',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-04-30 14:33:57',
                'updated_at' => '2021-04-30 14:33:57',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 106,
                'rank_id' => 1,
                'identification' => 'dynamic1229',
                'name' => '김상일',
                'email' => '',
                'phone_number' => '010-9797-9797',
                'phone_first' => '010',
                'phone_center' => '9797',
                'phone_last' => '9797',
                'resident_registration_number' => '',
                'password' => '$2y$10$jBlCtFr1z.9khn/xkYy3JuaxWfuHYeHwKftfDi6TyIbJxcHORgjk.',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-05-03 10:29:34',
                'updated_at' => '2021-05-03 10:29:34',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 107,
                'rank_id' => 4,
                'identification' => '예지예지',
                'name' => '예지지지',
                'email' => '',
                'phone_number' => '010-3772-2311',
                'phone_first' => '010',
                'phone_center' => '3772',
                'phone_last' => '2311',
                'resident_registration_number' => '',
                'password' => '$2y$10$VjqkY46lGA4UcsOxwV5TUeLmxmg8j79IL9dGtMkpuYNn.c432vt4a',
                'bank_information' => '',
                'virtual_account_information' => '',
                'holding_deposit' => NULL,
                'affiliate_name' => '예지예지',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-05-06 13:08:52',
                'updated_at' => '2021-05-06 13:08:52',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 108,
                'rank_id' => 3,
                'identification' => 'soonhyeon12',
                'name' => '의정부 민락점 테스트',
                'email' => '',
                'phone_number' => '010-2123-6546',
                'phone_first' => '010',
                'phone_center' => '2123',
                'phone_last' => '6546',
                'resident_registration_number' => '',
                'password' => '$2y$10$KwAlkb35qTGSlZfVNBprmedPw5SVpIBpaypL38iTFUetsw3l5RpYO',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-05-06 17:43:17',
                'updated_at' => '2021-05-06 17:43:17',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 109,
                'rank_id' => 6,
                'identification' => 'alba1',
                'name' => '알바생1',
                'email' => '',
                'phone_number' => '000-1111-2354',
                'phone_first' => '000',
                'phone_center' => '1111',
                'phone_last' => '2354',
                'resident_registration_number' => '',
                'password' => '$2y$10$sy8sVL6f0DzuUrT1h1thBOO1Zti8hVTtYO9D8kfgi4ZPXzF7jIppa',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-05-07 09:13:23',
                'updated_at' => '2021-05-07 09:13:23',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 110,
                'rank_id' => 6,
                'identification' => 'alba2',
                'name' => '알바생2',
                'email' => '',
                'phone_number' => '010-2222-4567',
                'phone_first' => '010',
                'phone_center' => '2222',
                'phone_last' => '4567',
                'resident_registration_number' => '',
                'password' => '$2y$10$f/qoJdxfWqG7IzM2/Sg0D.PComlnwdX8EkoFa3QQE9uIqluVjRoRS',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-05-07 09:14:01',
                'updated_at' => '2021-05-07 09:14:01',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 111,
                'rank_id' => 3,
                'identification' => '이용희차장',
                'name' => '이용희',
                'email' => '',
                'phone_number' => '010-8373-7262',
                'phone_first' => '010',
                'phone_center' => '8373',
                'phone_last' => '7262',
                'resident_registration_number' => '',
                'password' => '$2y$10$glJs3ePFDl3aMXEyu6n.zeCQGDGTIpVUKs5SwtKY9FPeAvRO7LIzu',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-05-10 17:09:42',
                'updated_at' => '2021-05-10 17:09:42',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 112,
                'rank_id' => 3,
                'identification' => '차윤서대리',
                'name' => '차윤서',
                'email' => '',
                'phone_number' => '010-4737-2222',
                'phone_first' => '010',
                'phone_center' => '4737',
                'phone_last' => '2222',
                'resident_registration_number' => '',
                'password' => '$2y$10$zCKUMANWAsEVbQOveSYEB.PEWZb0W1n/VKPmxGU9goHsIwFuiDwZO',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-05-10 17:11:55',
                'updated_at' => '2021-05-10 17:11:55',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 113,
                'rank_id' => 3,
                'identification' => '박유진대리',
                'name' => '박유진',
                'email' => '',
                'phone_number' => '010-3939-0101',
                'phone_first' => '010',
                'phone_center' => '3939',
                'phone_last' => '0101',
                'resident_registration_number' => '',
                'password' => '$2y$10$E4/Rk.lBwJMufhgEQMbFCuJFdrZbQ1XPbJC9aTn3ubJtsfGs3X0c2',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-05-10 17:12:27',
                'updated_at' => '2021-05-10 17:12:27',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 114,
                'rank_id' => 4,
                'identification' => 'supplier1',
                'name' => 'supplier1',
                'email' => 'luongkimtienit198@gmail.com',
                'phone_number' => '231-1231-1231',
                'phone_first' => '231',
                'phone_center' => '1231',
                'phone_last' => '1231',
                'resident_registration_number' => '21321312',
                'password' => '$2y$10$LcYgYsYtS1SDbgM4c8egWeBKDeg0Y/trYYEmWSaA.7A3ZbQOsKd46',
                'bank_information' => 'Tien Luong',
                'virtual_account_information' => '234',
                'holding_deposit' => NULL,
                'affiliate_name' => 'nhacungcap',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-05-28 11:06:32',
                'updated_at' => '2021-05-28 11:06:32',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 115,
                'rank_id' => 3,
                'identification' => 'owner1',
                'name' => 'owner1',
                'email' => 'luongkimtien@enjoyworks.co.kr',
                'phone_number' => '213-1231-1232',
                'phone_first' => '213',
                'phone_center' => '1231',
                'phone_last' => '1232',
                'resident_registration_number' => '23123132',
                'password' => '$2y$10$yCS1IRiE6XN5f/b7aHP.GuZFRGsdH0AgwllJ4KDW7nNwEJfy/krfC',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-05-31 10:52:03',
                'updated_at' => '2021-05-31 10:52:03',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 116,
                'rank_id' => 3,
                'identification' => 'owner2',
                'name' => 'owner2',
                'email' => 'luongkimtien@enjoyworks.co.kr',
                'phone_number' => '312-1232-1232',
                'phone_first' => '312',
                'phone_center' => '1232',
                'phone_last' => '1232',
                'resident_registration_number' => '123123213213',
                'password' => '$2y$10$78vGxVbWeXxVcSOQubdpXOlgRiCu57TcyfZk0kC.Eghm0wHPoNbEK',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-06-02 11:12:01',
                'updated_at' => '2021-06-02 11:12:01',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 117,
                'rank_id' => 1,
                'identification' => 'tienadmin',
                'name' => 'tienadmin1',
                'email' => 'luongkimtien@enjoyworks.co.kr',
                'phone_number' => '124-1241-1241',
                'phone_first' => '124',
                'phone_center' => '1241',
                'phone_last' => '1241',
                'resident_registration_number' => '',
                'password' => '$2y$10$tKXWf85G0lCAt9QAEfOUXuUMjvPAtniwxNWr/nWQDweGj7z4d/paC',
                'bank_information' => NULL,
                'virtual_account_information' => NULL,
                'holding_deposit' => NULL,
                'affiliate_name' => '',
                'account_number' => '',
                'firebase_token' => NULL,
                'created_at' => '2021-06-04 14:53:22',
                'updated_at' => '2021-06-04 14:53:22',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}