<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'userAA',
                'email' => 'usera@gmail.com',
                'email_verified_at' => '0000-00-00 00:00:00',
                'password' => '12345678',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => '',
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '099-5135-5135',
                'point' => '1000',
                'total_purchase_amount' => '0',
                'level' => '1',
                'firebase_token' => 'dWm23Uy2Z0M:APA91bHsSGbqe70TPThO1QXmQlDc2bZJCiIzk26RFvYpX1nSP0n61n51MF9W_j_gJP6sh7C1xESsqaNkECqRhKPS-TC0msHnGwcjVjPH4SAjX3ZNFBGP3gVKEpW4zBr5nq8pwenQ2hXG',
                'push' => 'N',
                'created_at' => '2021-03-16 10:20:21',
                'updated_at' => '2021-06-04 15:36:21',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'userB',
                'email' => 'userB@gmail.com',
                'email_verified_at' => '0000-00-00 00:00:00',
                'password' => '123456',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '059-5135-5135',
                'point' => NULL,
                'total_purchase_amount' => '0',
                'level' => '0',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-02-16 10:20:21',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'alsrnjs',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '12345678',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '010-2222-2222',
                'point' => '0',
                'total_purchase_amount' => '0',
                'level' => '1',
                'firebase_token' => 'dRVfCFjAf4k:APA91bGXKfG_ZN8cYeD3lE6QhTR6-9xMcMwxVYj-uCGB5eHxCGxpicM7jYD882_GooOr82AXssjf2vKpxUbFcakFLwnPhC_NeG_Hi-ErhNxVzCx4zu7trGZA9N8L1bmxj498v7ZuZ-06',
                'push' => 'Y',
                'created_at' => NULL,
                'updated_at' => '2021-04-01 09:11:50',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 23,
                'name' => 'hoquan',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'hoquan123',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '0339301877',
                'point' => NULL,
                'total_purchase_amount' => '0',
                'level' => '0',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-03-17 18:21:25',
                'updated_at' => '2021-03-17 18:21:25',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 24,
                'name' => 'hoquan1',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'hoquan123',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '01012345123',
                'point' => NULL,
                'total_purchase_amount' => '0',
                'level' => '0',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-03-18 12:24:11',
                'updated_at' => '2021-03-18 12:24:11',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 25,
                'name' => 'Hồ Quận',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'hoquan123',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '01012341234',
                'point' => NULL,
                'total_purchase_amount' => '0',
                'level' => '0',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-03-18 12:24:56',
                'updated_at' => '2021-03-18 12:24:56',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 26,
                'name' => 'hoquanAb',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'hoquan1234',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '01012340000',
                'point' => NULL,
                'total_purchase_amount' => '0',
                'level' => '0',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-03-18 12:30:38',
                'updated_at' => '2021-03-18 12:30:38',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 27,
                'name' => 'hoquanAb34',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'hoquan1234',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '01012340001',
                'point' => NULL,
                'total_purchase_amount' => '0',
                'level' => '0',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-03-18 13:16:12',
                'updated_at' => '2021-06-03 17:23:20',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 28,
                'name' => 'phan hồ',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'hoquan1234',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '012-3456-1234',
                'point' => NULL,
                'total_purchase_amount' => '0',
                'level' => '0',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-03-18 14:52:08',
                'updated_at' => '2021-03-18 14:52:08',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 29,
                'name' => 'hoquan12',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'hoquan1234',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '091-2312-3123',
                'point' => NULL,
                'total_purchase_amount' => '0',
                'level' => '0',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-03-18 14:54:20',
                'updated_at' => '2021-03-18 14:54:20',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 30,
                'name' => 'Hồ Quận1',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'hoquan123',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '090-1121-2312',
                'point' => NULL,
                'total_purchase_amount' => '0',
                'level' => '0',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-03-18 15:10:21',
                'updated_at' => '2021-03-18 15:10:21',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 31,
                'name' => 'quan',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'hoquan1234',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '012-3456-7890',
                'point' => NULL,
                'total_purchase_amount' => '0',
                'level' => '0',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-03-18 15:19:21',
                'updated_at' => '2021-03-18 15:19:21',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 32,
                'name' => 'Hồ Quận',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'hoquan123',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '312-3123-1231',
                'point' => NULL,
                'total_purchase_amount' => '0',
                'level' => '0',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-03-18 15:28:57',
                'updated_at' => '2021-03-18 15:28:57',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 33,
                'name' => '닉넴넴',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '12345678',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => 'user_profile_1617690464.jpg',
                'phone_number' => '010-1234-5678',
                'point' => '10000',
                'total_purchase_amount' => '0',
                'level' => '0',
                'firebase_token' => 'dK7pfqERXWw:APA91bFtYqe7AcxPigZfH8XA1rWsQPJqDHCW73QZMvAw2BH63NevMfAZQVt3OXizkebJW0YGqJX5m5lmFo3HTzHhTCbVFKel_xXuokHmCcZ22iJrHeL2GAUqX-2X1yQTtZ0qA6pPKQZR',
                'push' => 'N',
                'created_at' => '2021-03-18 15:38:06',
                'updated_at' => '2021-04-06 15:27:44',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 34,
                'name' => 'quan123',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'hoquan123',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '109-2312-3123',
                'point' => NULL,
                'total_purchase_amount' => '0',
                'level' => '0',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-03-18 18:34:03',
                'updated_at' => '2021-03-18 18:34:03',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 35,
                'name' => 'minhtinh',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'minhtinh123',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '011-1235-4321',
                'point' => '21323867',
                'total_purchase_amount' => '0',
                'level' => '2',
                'firebase_token' => '',
                'push' => 'Y',
                'created_at' => '2021-03-19 17:15:01',
                'updated_at' => '2021-05-04 15:09:41',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 36,
                'name' => 'quan',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'quan123456',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '010-6666-6667',
                'point' => '0',
                'total_purchase_amount' => '0',
                'level' => '1',
                'firebase_token' => '',
                'push' => 'Y',
                'created_at' => '2021-03-24 10:29:23',
                'updated_at' => '2021-04-02 12:15:33',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 37,
                'name' => 'quan3',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'quan123456',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => 'user_profile_1618364475.jpg',
                'phone_number' => '010-6666-6669',
                'point' => '0',
                'total_purchase_amount' => '0',
                'level' => '1',
                'firebase_token' => 'dbeO8c84ju8:APA91bHkRYxSC6p2yaEwQzD0XL60BWDUitYnDwS_DO-p4CBK3XD22QJQ6bGWG3k7Z3mh2hYw-wCnIDF96k00NKWyE1xGHXxZHnXJfzys8FegV6NGP2nxSEjW6FMYjWits9ovFql4rjKQ',
                'push' => 'Y',
                'created_at' => '2021-03-24 12:11:26',
                'updated_at' => '2021-04-29 16:25:36',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 38,
                'name' => 'aaa',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '111111111',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '453-4545-4543',
                'point' => '0',
                'total_purchase_amount' => '0',
                'level' => '1',
                'firebase_token' => 'dbeO8c84ju8:APA91bHkRYxSC6p2yaEwQzD0XL60BWDUitYnDwS_DO-p4CBK3XD22QJQ6bGWG3k7Z3mh2hYw-wCnIDF96k00NKWyE1xGHXxZHnXJfzys8FegV6NGP2nxSEjW6FMYjWits9ovFql4rjKQ',
                'push' => 'N',
                'created_at' => '2021-03-29 16:14:22',
                'updated_at' => '2021-04-29 11:29:33',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 39,
                'name' => 'ab',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '11111111',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => 'user_profile_1617875892.jpg',
                'phone_number' => '090-5737-0270',
                'point' => '90000001123',
                'total_purchase_amount' => '0',
                'level' => '2',
                'firebase_token' => 'eVxkJy4u7os:APA91bFd_NMAMNUGAMuUk4409ZYsb8Jn0ZRtkfURbKUqPfeysqUQfk8RjiBtGiShnpWlk-genSlf2zG7lNR_nKEIEx8UPwTRrsJgEVDkBzIr-zbUTCjq3T-bn_EeZP9aBRMFAdi0VsDK',
                'push' => 'Y',
                'created_at' => '2021-03-29 17:06:32',
                'updated_at' => '2021-05-05 15:24:53',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 40,
                'name' => 'moon1234',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'ppppppp1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => 'user_profile_1617245735.jpg',
                'phone_number' => '090-5737-0271',
                'point' => '0',
                'total_purchase_amount' => '0',
                'level' => '1',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-03-29 17:08:28',
                'updated_at' => '2021-04-01 11:55:36',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 41,
                'name' => 'tien123',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '123456',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '100-1000-1000',
                'point' => '0',
                'total_purchase_amount' => '0',
                'level' => '1',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 42,
                'name' => 'tien',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '12345678',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => 'user_profile_1617351969.jpg',
                'phone_number' => '700-0000-0001',
                'point' => '20',
                'total_purchase_amount' => '0',
                'level' => '1',
                'firebase_token' => 'eVxkJy4u7os:APA91bFd_NMAMNUGAMuUk4409ZYsb8Jn0ZRtkfURbKUqPfeysqUQfk8RjiBtGiShnpWlk-genSlf2zG7lNR_nKEIEx8UPwTRrsJgEVDkBzIr-zbUTCjq3T-bn_EeZP9aBRMFAdi0VsDK',
                'push' => 'N',
                'created_at' => '2021-04-01 13:23:25',
                'updated_at' => '2021-04-19 11:37:43',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 43,
                'name' => '문구방구',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'qkrrlwjd1',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => 'user_profile_1617841732.jpg',
                'phone_number' => '010-3612-1161',
                'point' => '1126116',
                'total_purchase_amount' => '5000',
                'level' => '1',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-04-07 10:01:34',
                'updated_at' => '2021-05-05 16:00:30',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 44,
                'name' => 'tienkim123',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '00000000',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => 'user_profile_1619678076.jpg',
                'phone_number' => '700-0000-0000',
                'point' => '250',
                'total_purchase_amount' => '1000000',
                'level' => '5',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-04-07 10:57:17',
                'updated_at' => '2021-04-29 15:34:36',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 45,
                'name' => 'sssss',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'qwer1234',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '010-2745-0675',
                'point' => '10',
                'total_purchase_amount' => '10000',
                'level' => '1',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-04-07 11:37:10',
                'updated_at' => '2021-05-04 17:01:02',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 46,
                'name' => 'Sin',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => 'quan123456',
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '010-8888-8888',
                'point' => '0',
                'total_purchase_amount' => '0',
                'level' => '1',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-04-28 12:22:29',
                'updated_at' => '2021-04-28 12:22:29',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 47,
                'name' => NULL,
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '010-1111-1111',
                'point' => '0',
                'total_purchase_amount' => '100',
                'level' => '1',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-05-04 14:15:12',
                'updated_at' => '2021-05-04 14:15:12',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 48,
                'name' => NULL,
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => NULL,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'current_team_id' => NULL,
                'profile_photo_path' => NULL,
                'phone_number' => '010-3939-8256',
                'point' => '123',
                'total_purchase_amount' => '123400',
                'level' => '2',
                'firebase_token' => NULL,
                'push' => 'N',
                'created_at' => '2021-05-04 14:23:12',
                'updated_at' => '2021-05-04 22:20:09',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}